alertmanager:
  alertmanagerSpec:
    replicas: 2
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    alertmanagerConfigMatcherStrategy:
      type: None

  service:
    type: NodePort
    nodePort: 30902

prometheus:
  service:
    type: NodePort
    nodePort: 30901

grafana:
  service:
    type: NodePort
    nodePort: 30903

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
