apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_PASSWORD: cm9vdA== # base64 for "root" & configured for webapp deployment env
  MYSQL_ROOT_PASSWORD: cm9vdA==   # base64 for "root" & configured for mysqldb statefulset env
